### PR TITLE
Add feature to auto-generate authors page

### PR DESCRIPTION
**Pull request by saugatmalla**
- Build author-header block for the authors page

Test Urls: 
Before: https://main--blog--adobecom.hlx.page/drafts/smalla/authors/adam-morgan
After: https://authors--blog--adobecom.hlx.page/drafts/smalla/authors/adam-morgan?martech=off

### CODE REVIEW

**Review by rgclayton — APPROVED** [review]

**Review by JasonHowellSlavin — APPROVED** [review]
Looks like you add some of the same functions in PR https://github.com/adobecom/blog/pull/8/files. Is that intentional?

**Comment by saugatmalla** [comment]
> Looks like you add some of the same functions in PR https://github.com/adobecom/blog/pull/8/files. Is that intentional?

@JasonHowellSlavin  Yeah, I wanted to keep both PR separate, but these share some of the same code. They will be merged to one after.

**Comment by rgclayton** [comment]
Will merge in the morning if there are no objections.

**Comment by rgclayton** [comment]
@saugatmalla can you take a look at the conflicts?

**Comment by saugatmalla** [comment]
> @saugatmalla can you take a look at the conflicts?

Fixed merge conflict. 
@rgclayton

**Pull request merged**
